version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/base
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
      - elasticsearch

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - celery
